#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OpenIZMobile.Resource", IsApplication=true)]

namespace OpenIZMobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::OpenIZ.Mobile.Core.Android.Resource.Id.contentFrame = global::OpenIZMobile.Resource.Id.contentFrame;
			global::OpenIZ.Mobile.Core.Android.Resource.Layout.zxingscanneractivitylayout = global::OpenIZMobile.Resource.Layout.zxingscanneractivitylayout;
			global::OpenIZ.Mobile.Core.Android.Resource.Layout.zxingscannerfragmentlayout = global::OpenIZMobile.Resource.Layout.zxingscannerfragmentlayout;
			global::OpenIZ.Mobile.Core.Android.Resource.String.ApplicationName = global::OpenIZMobile.Resource.String.ApplicationName;
			global::OpenIZ.Mobile.Core.Android.Resource.String.Hello = global::OpenIZMobile.Resource.String.Hello;
			global::OpenIZ.Mobile.Core.Android.Resource.String.applet_confirm_close = global::OpenIZMobile.Resource.String.applet_confirm_close;
			global::OpenIZ.Mobile.Core.Android.Resource.String.cancel = global::OpenIZMobile.Resource.String.cancel;
			global::OpenIZ.Mobile.Core.Android.Resource.String.confirm = global::OpenIZMobile.Resource.String.confirm;
			global::OpenIZ.Mobile.Core.Android.Resource.String.err_general = global::OpenIZMobile.Resource.String.err_general;
			global::OpenIZ.Mobile.Core.Android.Resource.String.err_oauth2_invalid_client = global::OpenIZMobile.Resource.String.err_oauth2_invalid_client;
			global::OpenIZ.Mobile.Core.Android.Resource.String.err_oauth2_invalid_grant = global::OpenIZMobile.Resource.String.err_oauth2_invalid_grant;
			global::OpenIZ.Mobile.Core.Android.Resource.String.err_oauth2_invalid_request = global::OpenIZMobile.Resource.String.err_oauth2_invalid_request;
			global::OpenIZ.Mobile.Core.Android.Resource.String.err_oauth2_invalid_scope = global::OpenIZMobile.Resource.String.err_oauth2_invalid_scope;
			global::OpenIZ.Mobile.Core.Android.Resource.String.err_oauth2_unauthorized_client = global::OpenIZMobile.Resource.String.err_oauth2_unauthorized_client;
			global::OpenIZ.Mobile.Core.Android.Resource.String.err_oauth2_unsupported_grant_type = global::OpenIZMobile.Resource.String.err_oauth2_unsupported_grant_type;
			global::OpenIZ.Mobile.Core.Android.Resource.String.err_token_InvalidSignature = global::OpenIZMobile.Resource.String.err_token_InvalidSignature;
			global::OpenIZ.Mobile.Core.Android.Resource.String.err_token_InvalidTokenType = global::OpenIZMobile.Resource.String.err_token_InvalidTokenType;
			global::OpenIZ.Mobile.Core.Android.Resource.String.err_token_KeyNotFound = global::OpenIZMobile.Resource.String.err_token_KeyNotFound;
			global::OpenIZ.Mobile.Core.Android.Resource.String.err_token_NotYetValid = global::OpenIZMobile.Resource.String.err_token_NotYetValid;
			global::OpenIZ.Mobile.Core.Android.Resource.String.err_token_TokenExpired = global::OpenIZMobile.Resource.String.err_token_TokenExpired;
			global::OpenIZ.Mobile.Core.Android.Resource.String.library_name = global::OpenIZMobile.Resource.String.library_name;
			global::OpenIZ.Mobile.Core.Android.Resource.String.startup_configuration = global::OpenIZMobile.Resource.String.startup_configuration;
			global::OpenIZ.Mobile.Core.Android.Resource.String.startup_data = global::OpenIZMobile.Resource.String.startup_data;
			global::OpenIZ.Mobile.Core.Android.Resource.String.startup_setup = global::OpenIZMobile.Resource.String.startup_setup;
			global::OpenIZ.Mobile.Core.Android.Resource.String.startup_update = global::OpenIZMobile.Resource.String.startup_update;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::OpenIZMobile.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::OpenIZMobile.Resource.String.Hello;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::OpenIZMobile.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::OpenIZMobile.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::OpenIZMobile.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int horizontalSpacing = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int layout_breakLine = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int layout_horizontalSpacing = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int verticalSpacing = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blue_gradient = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int circle_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int gray_gradient = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int logo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int logo_lg = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int orange_gradient = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int splash_gradient = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int applet_view = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int contentFrame = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int txt_splash_info = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int txt_splash_version = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Applet = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Splash = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int zxingscanneractivitylayout = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int zxingscannerfragmentlayout = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f05002f
			public const int activity_login = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int activity_setup = 2131034160;
			
			// aapt resource value: 0x7f050016
			public const int app_name = 2131034134;
			
			// aapt resource value: 0x7f050005
			public const int applet_confirm_close = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int cancel = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int confirm = 2131034115;
			
			// aapt resource value: 0x7f050031
			public const int err_applet_not_found = 2131034161;
			
			// aapt resource value: 0x7f050035
			public const int err_exception = 2131034165;
			
			// aapt resource value: 0x7f050006
			public const int err_general = 2131034118;
			
			// aapt resource value: 0x7f050033
			public const int err_login = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int err_login_invalidusername = 2131034164;
			
			// aapt resource value: 0x7f050008
			public const int err_oauth2_invalid_client = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int err_oauth2_invalid_grant = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int err_oauth2_invalid_request = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int err_oauth2_invalid_scope = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int err_oauth2_unauthorized_client = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int err_oauth2_unsupported_grant_type = 2131034123;
			
			// aapt resource value: 0x7f050036
			public const int err_online_required = 2131034166;
			
			// aapt resource value: 0x7f050032
			public const int err_startup = 2131034162;
			
			// aapt resource value: 0x7f05000e
			public const int err_token_InvalidSignature = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int err_token_InvalidTokenType = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int err_token_KeyNotFound = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int err_token_NotYetValid = 2131034129;
			
			// aapt resource value: 0x7f05000d
			public const int err_token_TokenExpired = 2131034125;
			
			// aapt resource value: 0x7f05001d
			public const int installing_applets = 2131034141;
			
			// aapt resource value: 0x7f05002c
			public const int joinRealm = 2131034156;
			
			// aapt resource value: 0x7f05002e
			public const int leaveRealm = 2131034158;
			
			// aapt resource value: 0x7f050002
			public const int library_name = 2131034114;
			
			// aapt resource value: 0x7f05001f
			public const int loading = 2131034143;
			
			// aapt resource value: 0x7f050019
			public const int login = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int login_title = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int needs_setup = 2131034140;
			
			// aapt resource value: 0x7f05002d
			public const int noRealm = 2131034157;
			
			// aapt resource value: 0x7f050018
			public const int password = 2131034136;
			
			// aapt resource value: 0x7f05002a
			public const int setting_log = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int setting_log_desc = 2131034155;
			
			// aapt resource value: 0x7f050028
			public const int setting_offline_only = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int setting_offline_only_desc = 2131034153;
			
			// aapt resource value: 0x7f050021
			public const int setup_subTitle = 2131034145;
			
			// aapt resource value: 0x7f050025
			public const int setup_subTitle_app = 2131034149;
			
			// aapt resource value: 0x7f050027
			public const int setup_subTitle_lnf = 2131034151;
			
			// aapt resource value: 0x7f050023
			public const int setup_subTitle_sec = 2131034147;
			
			// aapt resource value: 0x7f050020
			public const int setup_title = 2131034144;
			
			// aapt resource value: 0x7f050024
			public const int setup_title_app = 2131034148;
			
			// aapt resource value: 0x7f050026
			public const int setup_title_lnf = 2131034150;
			
			// aapt resource value: 0x7f050022
			public const int setup_title_sec = 2131034146;
			
			// aapt resource value: 0x7f05001e
			public const int starting_services = 2131034142;
			
			// aapt resource value: 0x7f05001b
			public const int startup = 2131034139;
			
			// aapt resource value: 0x7f050012
			public const int startup_configuration = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int startup_data = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int startup_setup = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int startup_update = 2131034132;
			
			// aapt resource value: 0x7f050017
			public const int user_name = 2131034135;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060005
			public const int ActionBar = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int AppletTile = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int BlueTitle = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int DefaultFont = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int GrayTitle = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int OpenIZ = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int OpenIZ_NoTitle = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int OpenIZ_Splash = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int SoftInputMode = 2131099654;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FlowLayout = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int FlowLayout_horizontalSpacing = 0;
			
			// aapt resource value: 1
			public const int FlowLayout_verticalSpacing = 1;
			
			public static int[] FlowLayout_LayoutParams = new int[] {
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int FlowLayout_LayoutParams_layout_breakLine = 0;
			
			// aapt resource value: 1
			public const int FlowLayout_LayoutParams_layout_horizontalSpacing = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
