#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OpenIZMobile.Resource", IsApplication=true)]

namespace OpenIZMobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::OpenIZ.Mobile.Core.Android.Resource.String.applet_confirm_close = global::OpenIZMobile.Resource.String.applet_confirm_close;
			global::OpenIZ.Mobile.Core.Android.Resource.String.cancel = global::OpenIZMobile.Resource.String.cancel;
			global::OpenIZ.Mobile.Core.Android.Resource.String.confirm = global::OpenIZMobile.Resource.String.confirm;
			global::OpenIZ.Mobile.Core.Android.Resource.String.err_general = global::OpenIZMobile.Resource.String.err_general;
			global::OpenIZ.Mobile.Core.Android.Resource.String.err_oauth2_invalid_client = global::OpenIZMobile.Resource.String.err_oauth2_invalid_client;
			global::OpenIZ.Mobile.Core.Android.Resource.String.err_oauth2_invalid_grant = global::OpenIZMobile.Resource.String.err_oauth2_invalid_grant;
			global::OpenIZ.Mobile.Core.Android.Resource.String.err_oauth2_invalid_request = global::OpenIZMobile.Resource.String.err_oauth2_invalid_request;
			global::OpenIZ.Mobile.Core.Android.Resource.String.err_oauth2_invalid_scope = global::OpenIZMobile.Resource.String.err_oauth2_invalid_scope;
			global::OpenIZ.Mobile.Core.Android.Resource.String.err_oauth2_unauthorized_client = global::OpenIZMobile.Resource.String.err_oauth2_unauthorized_client;
			global::OpenIZ.Mobile.Core.Android.Resource.String.err_oauth2_unsupported_grant_type = global::OpenIZMobile.Resource.String.err_oauth2_unsupported_grant_type;
			global::OpenIZ.Mobile.Core.Android.Resource.String.err_token_InvalidSignature = global::OpenIZMobile.Resource.String.err_token_InvalidSignature;
			global::OpenIZ.Mobile.Core.Android.Resource.String.err_token_InvalidTokenType = global::OpenIZMobile.Resource.String.err_token_InvalidTokenType;
			global::OpenIZ.Mobile.Core.Android.Resource.String.err_token_KeyNotFound = global::OpenIZMobile.Resource.String.err_token_KeyNotFound;
			global::OpenIZ.Mobile.Core.Android.Resource.String.err_token_NotYetValid = global::OpenIZMobile.Resource.String.err_token_NotYetValid;
			global::OpenIZ.Mobile.Core.Android.Resource.String.err_token_TokenExpired = global::OpenIZMobile.Resource.String.err_token_TokenExpired;
			global::OpenIZ.Mobile.Core.Android.Resource.String.library_name = global::OpenIZMobile.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int horizontalSpacing = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int layout_breakLine = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int layout_horizontalSpacing = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int verticalSpacing = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int aefi = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int announce = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int app = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int app_alt = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int appbar = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int baby = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int blue_gradient = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int brick = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int calendar = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int check = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int checkin = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int circle_bg = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int coat_of_arms_of_tanzania = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int cogs = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int drk_aefi = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int drk_announce = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int drk_applet = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int drk_applet_alt = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int drk_baby = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int drk_barcode = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int drk_bed = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int drk_brick = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int drk_calendar = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int drk_check = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int drk_checkin = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int drk_cogs = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int drk_delete = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int drk_encounters = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int drk_facility = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int drk_foot = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int drk_grid = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int drk_group = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int drk_help = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int drk_home = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int drk_logout = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int drk_patient = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int drk_patient_alt = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int drk_patient_search = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int drk_patient_search_alt = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int drk_queue = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int drk_register_patient = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int drk_shield = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int drk_stock = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int drk_temp = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int drk_user = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int drk_weigh = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int encounters = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int facility = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int foot = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int gray_gradient = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int grid = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int group = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int help = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int home = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int logo = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int logo_lg = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int logout = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int orange_gradient = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int patient = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int patient_alt = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int patient_search = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int patient_search_alt = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int queue = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int register_patient = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int shield = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int splash_gradient = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int stock = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int tanzaniaflagmap = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int temp = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int weigh = 2130837574;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int applet_view = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int txt_splash_info = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int txt_splash_version = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Applet = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Splash = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050024
			public const int activity_login = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int activity_setup = 2131034149;
			
			// aapt resource value: 0x7f050010
			public const int app_name = 2131034128;
			
			// aapt resource value: 0x7f050003
			public const int applet_confirm_close = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int cancel = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int confirm = 2131034113;
			
			// aapt resource value: 0x7f050026
			public const int err_applet_not_found = 2131034150;
			
			// aapt resource value: 0x7f05002a
			public const int err_exception = 2131034154;
			
			// aapt resource value: 0x7f050004
			public const int err_general = 2131034116;
			
			// aapt resource value: 0x7f050028
			public const int err_login = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int err_login_invalidusername = 2131034153;
			
			// aapt resource value: 0x7f050006
			public const int err_oauth2_invalid_client = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int err_oauth2_invalid_grant = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int err_oauth2_invalid_request = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int err_oauth2_invalid_scope = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int err_oauth2_unauthorized_client = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int err_oauth2_unsupported_grant_type = 2131034121;
			
			// aapt resource value: 0x7f050027
			public const int err_startup = 2131034151;
			
			// aapt resource value: 0x7f05000c
			public const int err_token_InvalidSignature = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int err_token_InvalidTokenType = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int err_token_KeyNotFound = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int err_token_NotYetValid = 2131034127;
			
			// aapt resource value: 0x7f05000b
			public const int err_token_TokenExpired = 2131034123;
			
			// aapt resource value: 0x7f050017
			public const int installing_applets = 2131034135;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050013
			public const int login = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int login_title = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int needs_setup = 2131034134;
			
			// aapt resource value: 0x7f050012
			public const int password = 2131034130;
			
			// aapt resource value: 0x7f050022
			public const int setting_log = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int setting_log_desc = 2131034147;
			
			// aapt resource value: 0x7f050020
			public const int setting_offline_only = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int setting_offline_only_desc = 2131034145;
			
			// aapt resource value: 0x7f050019
			public const int setup_subTitle = 2131034137;
			
			// aapt resource value: 0x7f05001d
			public const int setup_subTitle_app = 2131034141;
			
			// aapt resource value: 0x7f05001f
			public const int setup_subTitle_lnf = 2131034143;
			
			// aapt resource value: 0x7f05001b
			public const int setup_subTitle_sec = 2131034139;
			
			// aapt resource value: 0x7f050018
			public const int setup_title = 2131034136;
			
			// aapt resource value: 0x7f05001c
			public const int setup_title_app = 2131034140;
			
			// aapt resource value: 0x7f05001e
			public const int setup_title_lnf = 2131034142;
			
			// aapt resource value: 0x7f05001a
			public const int setup_title_sec = 2131034138;
			
			// aapt resource value: 0x7f050015
			public const int startup = 2131034133;
			
			// aapt resource value: 0x7f050011
			public const int user_name = 2131034129;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060005
			public const int ActionBar = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int AppletTile = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int BlueTitle = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int DefaultFont = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int GrayTitle = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int OpenIZ = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int OpenIZ_NoTitle = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int OpenIZ_Splash = 2131099655;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FlowLayout = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int FlowLayout_horizontalSpacing = 0;
			
			// aapt resource value: 1
			public const int FlowLayout_verticalSpacing = 1;
			
			public static int[] FlowLayout_LayoutParams = new int[] {
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int FlowLayout_LayoutParams_layout_breakLine = 0;
			
			// aapt resource value: 1
			public const int FlowLayout_LayoutParams_layout_horizontalSpacing = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
