//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenIZ.Mobile.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenIZ.Mobile.Core.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server has detected a change conflict on an object you&apos;re attempting to update..
        /// </summary>
        internal static string Conflict {
            get {
                return ResourceManager.GetString("Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server has a newer version of the object you&apos;re trying to update.
        /// </summary>
        internal static string DBPE002 {
            get {
                return ResourceManager.GetString("DBPE002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;The server encountered an internal error while processing your request. Please contact the system administrator for more information. Include the following diagnostic error data:&lt;/p&gt;&lt;pre&gt;{0}&lt;/pre&gt;.
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is locked.
        /// </summary>
        internal static string locale_accountLocked {
            get {
                return ResourceManager.GetString("locale_accountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is deleted.
        /// </summary>
        internal static string locale_accountObsolete {
            get {
                return ResourceManager.GetString("locale_accountObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing imported data....
        /// </summary>
        internal static string locale_calculateImportedCareplan {
            get {
                return ResourceManager.GetString("locale_calculateImportedCareplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating Appointment Proposals ({0} remaining)....
        /// </summary>
        internal static string locale_calculatingCarePlan {
            get {
                return ResourceManager.GetString("locale_calculatingCarePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimizing Databases....
        /// </summary>
        internal static string locale_compacting {
            get {
                return ResourceManager.GetString("locale_compacting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Downloading Remote Data.
        /// </summary>
        internal static string locale_downloadError {
            get {
                return ResourceManager.GetString("locale_downloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error downloading the specified resources: {0}.
        /// </summary>
        internal static string locale_downloadErrorBody {
            get {
                return ResourceManager.GetString("locale_downloadErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing Data....
        /// </summary>
        internal static string locale_import {
            get {
                return ResourceManager.GetString("locale_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import of remote data is complete.
        /// </summary>
        internal static string locale_importDoneBody {
            get {
                return ResourceManager.GetString("locale_importDoneBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Data Imported.
        /// </summary>
        internal static string locale_importDoneSubject {
            get {
                return ResourceManager.GetString("locale_importDoneSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error importing the data from the remote data source. More details are below:
        ///
        ///{0}.
        /// </summary>
        internal static string locale_importErrorBody {
            get {
                return ResourceManager.GetString("locale_importErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error importing remote data.
        /// </summary>
        internal static string locale_importErrorSubject {
            get {
                return ResourceManager.GetString("locale_importErrorSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructing Freetext Index.
        /// </summary>
        internal static string locale_indexing {
            get {
                return ResourceManager.GetString("locale_indexing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username / Password.
        /// </summary>
        internal static string locale_invalidUserNamePassword {
            get {
                return ResourceManager.GetString("locale_invalidUserNamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing {0} from bundle ({1} of {2})....
        /// </summary>
        internal static string locale_processBundle {
            get {
                return ResourceManager.GetString("locale_processBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to update facility plan....
        /// </summary>
        internal static string locale_refreshCarePlan {
            get {
                return ResourceManager.GetString("locale_refreshCarePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your facility plan is over a week old, do you want to recalculate it?.
        /// </summary>
        internal static string locale_refreshCarePlanPrompt {
            get {
                return ResourceManager.GetString("locale_refreshCarePlanPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;The server received the request to synchronize the data, however it rejected it due to an error &lt;strong&gt;{0}&lt;/strong&gt;. The changes the server attempted to process were:&lt;/p&gt;&lt;pre&gt;{1}&lt;/pre&gt;&lt;p&gt;The message has been quarantined, you can view the message in the sync centre.&lt;/p&gt;&lt;a href=&quot;#/core/sync&quot; class=&quot;btn btn-lg btn-info&quot;&gt;Visit Sync Centre&lt;/a&gt;.
        /// </summary>
        internal static string locale_rejectionBody {
            get {
                return ResourceManager.GetString("locale_rejectionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization Conflict.
        /// </summary>
        internal static string locale_rejectionSubject {
            get {
                return ResourceManager.GetString("locale_rejectionSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session is expired.
        /// </summary>
        internal static string locale_session_expired {
            get {
                return ResourceManager.GetString("locale_session_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error establishing session:.
        /// </summary>
        internal static string locale_sessionError {
            get {
                return ResourceManager.GetString("locale_sessionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying Data.
        /// </summary>
        internal static string locale_setting_deploy {
            get {
                return ResourceManager.GetString("locale_setting_deploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrating Data.
        /// </summary>
        internal static string locale_setting_migration {
            get {
                return ResourceManager.GetString("locale_setting_migration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Tables.
        /// </summary>
        internal static string locale_setting_table {
            get {
                return ResourceManager.GetString("locale_setting_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting care plan manager service....
        /// </summary>
        internal static string locale_start_careplan {
            get {
                return ResourceManager.GetString("locale_start_careplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading protocol {0}....
        /// </summary>
        internal static string locale_starting {
            get {
                return ResourceManager.GetString("locale_starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiating pull request....
        /// </summary>
        internal static string locale_startingPoll {
            get {
                return ResourceManager.GetString("locale_startingPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0} ({1} of {2})....
        /// </summary>
        internal static string locale_sync {
            get {
                return ResourceManager.GetString("locale_sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Error synchronizing data with remote server. This is usually caused by a conflict where this device tried to send an object ({1}) to the server but the server had a different version of that object.&lt;/p&gt;&lt;p&gt;For your reference, the error is:&lt;br/&gt;{0}&lt;/p&gt;.
        /// </summary>
        internal static string locale_syncErrorBody {
            get {
                return ResourceManager.GetString("locale_syncErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending object to the server.
        /// </summary>
        internal static string locale_syncErrorSubject {
            get {
                return ResourceManager.GetString("locale_syncErrorSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application has been installed successfully. The application is currently downloading remote data it needs to operate from the back-end system (known as the IMS). During this time, you may notice the application operates very slowly or some screens don&apos;t have data. That is normal until the synchronizing is complete. We&apos;ll let you know when the synchronization operation is done!
        ///
        ///Sincerely,
        ///- OpenIZ Community.
        /// </summary>
        internal static string locale_welcomeMessageBody {
            get {
                return ResourceManager.GetString("locale_welcomeMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to OpenIZ Disconnected Client Core!.
        /// </summary>
        internal static string locale_welcomeMessageSubject {
            get {
                return ResourceManager.GetString("locale_welcomeMessageSubject", resourceCulture);
            }
        }
    }
}
