#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OpenIZ.Mobile.Core.Android.Resource", IsApplication=false)]

namespace OpenIZ.Mobile.Core.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020003
			public static int applet_confirm_close = 2130837507;
			
			// aapt resource value: 0x7f020002
			public static int cancel = 2130837506;
			
			// aapt resource value: 0x7f020001
			public static int confirm = 2130837505;
			
			// aapt resource value: 0x7f020005
			public static int err_oauth2_invalid_client = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int err_oauth2_invalid_grant = 2130837510;
			
			// aapt resource value: 0x7f020004
			public static int err_oauth2_invalid_request = 2130837508;
			
			// aapt resource value: 0x7f020009
			public static int err_oauth2_invalid_scope = 2130837513;
			
			// aapt resource value: 0x7f020007
			public static int err_oauth2_unauthorized_client = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int err_oauth2_unsupported_grant_type = 2130837512;
			
			// aapt resource value: 0x7f02000b
			public static int err_token_InvalidSignature = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int err_token_InvalidTokenType = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int err_token_KeyNotFound = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int err_token_NotYetValid = 2130837518;
			
			// aapt resource value: 0x7f02000a
			public static int err_token_TokenExpired = 2130837514;
			
			// aapt resource value: 0x7f020000
			public static int library_name = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
