//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenIZ.Mobile.Core.Xamarin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenIZ.Mobile.Core.Xamarin.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General authentication error occurred.
        /// </summary>
        internal static string err_authentication_exception {
            get {
                return ResourceManager.GetString("err_authentication_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot restore from backup as the backup files do not exist.
        /// </summary>
        internal static string err_backupNotExist {
            get {
                return ResourceManager.GetString("err_backupNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified security certificate was not found.
        /// </summary>
        internal static string err_certificate_not_found {
            get {
                return ResourceManager.GetString("err_certificate_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately compact is not permitted at this time.
        /// </summary>
        internal static string err_compactNotPermitted {
            get {
                return ResourceManager.GetString("err_compactNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device has already been registered..
        /// </summary>
        internal static string err_duplicate_deviceName {
            get {
                return ResourceManager.GetString("err_duplicate_deviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package is already installed.
        /// </summary>
        internal static string err_duplicate_package_name {
            get {
                return ResourceManager.GetString("err_duplicate_package_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept header is not understood.
        /// </summary>
        internal static string err_invalid_accept {
            get {
                return ResourceManager.GetString("err_invalid_accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is of wrong type.
        /// </summary>
        internal static string err_invalid_argumentType {
            get {
                return ResourceManager.GetString("err_invalid_argumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username/Password.
        /// </summary>
        internal static string err_login_invalidusername {
            get {
                return ResourceManager.GetString("err_login_invalidusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication server cannot be contacted. Use the credentials you last used to access this device.
        /// </summary>
        internal static string err_offline_use_cache_creds {
            get {
                return ResourceManager.GetString("err_offline_use_cache_creds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A purge is not permitted on this application configuration. Perhaps you&apos;re set to online mode only?.
        /// </summary>
        internal static string err_purgeNotPermitted {
            get {
                return ResourceManager.GetString("err_purgeNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset is not supported from this configuration.
        /// </summary>
        internal static string err_reset_not_supported {
            get {
                return ResourceManager.GetString("err_reset_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response received from server.
        /// </summary>
        internal static string err_response_failed_validation {
            get {
                return ResourceManager.GetString("err_response_failed_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A restore is not permitted due to the configuration of this device. Perhaps you&apos;re in online only mode?.
        /// </summary>
        internal static string err_restoreNotPermitted {
            get {
                return ResourceManager.GetString("err_restoreNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A startup error occurred. The application cannot continue. Please contact support..
        /// </summary>
        internal static string err_startup_error {
            get {
                return ResourceManager.GetString("err_startup_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many certificates matched the criteria (perhaps search criteria is too vague?).
        /// </summary>
        internal static string err_too_many_certificate_matches {
            get {
                return ResourceManager.GetString("err_too_many_certificate_matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set context to unauthenticated principal.
        /// </summary>
        internal static string err_unauthenticated_principal {
            get {
                return ResourceManager.GetString("err_unauthenticated_principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flusing diagnostics queue....
        /// </summary>
        internal static string flushing_logFile {
            get {
                return ResourceManager.GetString("flushing_logFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate for publisher {0} is expired (expired on {1:yyyy-MMM-dd}). Do you want to ignore this error and continue?.
        /// </summary>
        internal static string locale_certificateExpired {
            get {
                return ResourceManager.GetString("locale_certificateExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server responded with an invalid certificate: {0}. Do you want to trust this certificate?.
        /// </summary>
        internal static string locale_certificateValidation {
            get {
                return ResourceManager.GetString("locale_certificateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}....
        /// </summary>
        internal static string locale_downloading {
            get {
                return ResourceManager.GetString("locale_downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The applet could not be installed because the verification stage failed..
        /// </summary>
        internal static string locale_invalidSignature {
            get {
                return ResourceManager.GetString("locale_invalidSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The applet {0} is not signed and its authenticity cannot be verified. Do you want to continue installation?.
        /// </summary>
        internal static string locale_unsignedAppletPrompt {
            get {
                return ResourceManager.GetString("locale_unsignedAppletPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The applet {0} is not signed or contains an invalid header. Your security settings do not allow for unsigned applets to be executed..
        /// </summary>
        internal static string locale_unsignedAppletsNotAllowed {
            get {
                return ResourceManager.GetString("locale_unsignedAppletsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The applet {0} published by {1} is not trusted. Do you want to continue to load / install this applet?.
        /// </summary>
        internal static string locale_untrustedPublisherPrompt {
            get {
                return ResourceManager.GetString("locale_untrustedPublisherPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        internal static string locale_updateCheck {
            get {
                return ResourceManager.GetString("locale_updateCheck", resourceCulture);
            }
        }
    }
}
