C:\Users\justi\Source\Repos\openizdc\Solution Items\Android
C:\Users\justi\Source\Repos\openizdc\Solution Items\Antlr3.Runtime.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\ExpressionEvaluator.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\filelist.bat
C:\Users\justi\Source\Repos\openizdc\Solution Items\jint.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\MARC.HI.EHRS.SVC.Auditing.Core.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\MARC.HI.EHRS.SVC.Auditing.Core.pdb
C:\Users\justi\Source\Repos\openizdc\Solution Items\MohawkCollege.Util.Console.Parameters.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\Net45
C:\Users\justi\Source\Repos\openizdc\Solution Items\Newtonsoft.Json.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\Newtonsoft.Json.xml
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.BusinessRules.JavaScript.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.BusinessRules.JavaScript.pdb
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Core.Alert.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Core.Alert.dll.mdb
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Core.Alert.pdb
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Core.Alert.XML
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Core.Applets.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Core.Applets.dll.mdb
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Core.Applets.pdb
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Core.Applets.XML
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Core.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Core.Model.AMI.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Core.Model.AMI.dll.mdb
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Core.Model.AMI.pdb
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Core.Model.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Core.Model.dll.mdb
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Core.Model.pdb
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Core.Model.RISI.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Core.Model.RISI.pdb
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Core.Model.ViewModelSerializers.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Core.Model.ViewModelSerializers.pdb
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Core.Model.XML
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Core.PCL.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Core.PCL.dll.mdb
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Core.PCL.pdb
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Core.PCL.XML
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Messaging.AMI.Client.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Messaging.AMI.Client.dll.mdb
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Messaging.AMI.Client.pdb
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Messaging.AMI.Client.XML
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Messaging.IMSI.Client.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Messaging.IMSI.Client.pdb
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Messaging.IMSI.Client.XML
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Messaging.RISI.Client.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Messaging.RISI.Client.pdb
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Messaging.RISI.Client.XML
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.OrmLite.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.OrmLite.pdb
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Protocol.Xml.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Protocol.Xml.dll.mdb
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Protocol.Xml.pdb
C:\Users\justi\Source\Repos\openizdc\Solution Items\OpenIZ.Protocol.Xml.Test.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\SharpCompress.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\signkey.jks
C:\Users\justi\Source\Repos\openizdc\Solution Items\SQLite.Net.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\Xamarin.Android.Support.v4.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\zlibnet.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\ZXing.Net.Mobile.Core.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\zxing.portable.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\ZXingNetMobile.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\Android\SQLite.Net.Platform.XamarinAndroid.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\Android\SQLitePCL.raw.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\Net45\Mono.Data.Sqlite.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\Net45\SQLite.Net.Platform.Generic.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\Net45\sqlite3.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\Net45\sqlite3.exe
C:\Users\justi\Source\Repos\openizdc\Solution Items\Net45\SQLitePCL.raw.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\Net45\System.Data.Portable.dll
C:\Users\justi\Source\Repos\openizdc\Solution Items\Net45\System.Transactions.Portable.dll
